### ISSUE TITLE
Add GitHub Action for Building FlavorLang's Interpreter & VS Code Extension

### ISSUE THREAD

**Issue by KennyOliver** [KennyOliver/FlavorLang#110]
# Add GitHub Action for Building FlavorLang's Interpreter & VS Code Extension

## Description

I'd like to add a GitHub Actions workflow to automate building:
- FlavorLang's interpreter's executable using the Makefile in the `/src` directory.
- The VS Code extension located in the `/vscode-extension` directory.

### 1. Triggers
  - Pushes to the main branch.
  - Pull requests targeting the main branch.
### 2. Perform the following steps
  - Checkout the repository.
  - Set up Node.js for building the VS Code extension.
  - Build & package the VS Code extension.
  - Build the FlavorLang interpreter.
  - Upload build artifacts for both the interpreter & VS Code extension.

## Proposed Workflow File
```yml
name: Build FlavorLang & VS Code Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FlavorLang & VS Code Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build VS Code extension
        working-directory: vscode-extension
        run: |
          npm ci
          npm run package-extension

      - name: Upload VS Code extension package
        uses: actions/upload-artifact@v3
        with:
          name: flavorlang-extension
          path: vscode-extension/*.vsix

      - name: Build FlavorLang interpreter
        working-directory: src
        run: make

      - name: Upload FlavorLang interpreter executable
        uses: actions/upload-artifact@v3
        with:
          name: flavorlang-interpreter
          path: src/flavor
```
## Artifacts

The workflow will upload the following:
1. **`flavorlang-extension`**: The `.vsix` file for the VS Code extension.
2. **`flavorlang-interpreter`**: The executable built from the `/src` directory.

## Testing Instructions
1. Commit the `build.yml` file to `.github/workflows/` in the repository.
2. Push a change to the main branch or create a pull request targeting main.
3. Monitor the workflow in the Actions tab of the repository.
4. Verify the generated artifacts by downloading them from the workflow run page.

## Next Steps
- Create the `build.yml` file in `.github/workflows`.
- Test the workflow.
- Verify that the artifacts are correct and usable.
